name: cs529_proj3
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - mlflow
  - pre-commit
  - ipython
  - librosa
  - databricks-sdk
  - ipykernel
  - pytorch=2.4.0.*
  - torchvision
  - torchaudio
  - cpuonly
  - lightning
