name: cs529_proj3
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - mlflow
  - pre-commit
  - ipython
  - librosa
  - databricks-sdk
  - ipykernel
  - torchvision
  - torch
  - libpng
  - libjpeg
